#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("TempModTest.Resource", IsApplication=true)]

namespace TempModTest
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
			global::Hoho.Android.UsbSerial.Resource.String.ApplicationName = global::TempModTest.Resource.String.ApplicationName;
			global::Hoho.Android.UsbSerial.Resource.String.Hello = global::TempModTest.Resource.String.Hello;
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int Icon = 2130837504;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f060007
			public const int Get = 2131099655;
			
			// aapt resource value: 0x7f060005
			public const int Init41 = 2131099653;
			
			// aapt resource value: 0x7f060006
			public const int Init42 = 2131099654;
			
			// aapt resource value: 0x7f060012
			public const int backToDeviceList = 2131099666;
			
			// aapt resource value: 0x7f06000e
			public const int clear = 2131099662;
			
			// aapt resource value: 0x7f06000b
			public const int consoleText = 2131099659;
			
			// aapt resource value: 0x7f06000a
			public const int demoScroller = 2131099658;
			
			// aapt resource value: 0x7f060001
			public const int demoTitle = 2131099649;
			
			// aapt resource value: 0x7f060004
			public const int deviceList = 2131099652;
			
			// aapt resource value: 0x7f060013
			public const int linearLayout1 = 2131099667;
			
			// aapt resource value: 0x7f060010
			public const int loadFromEEPROM = 2131099664;
			
			// aapt resource value: 0x7f06000f
			public const int loadFromFile = 2131099663;
			
			// aapt resource value: 0x7f060002
			public const int progressBar = 2131099650;
			
			// aapt resource value: 0x7f060000
			public const int progressBarTitle = 2131099648;
			
			// aapt resource value: 0x7f060011
			public const int saveToEEPROM = 2131099665;
			
			// aapt resource value: 0x7f060003
			public const int separator = 2131099651;
			
			// aapt resource value: 0x7f060009
			public const int sleepButton = 2131099657;
			
			// aapt resource value: 0x7f06000c
			public const int start = 2131099660;
			
			// aapt resource value: 0x7f06000d
			public const int stop = 2131099661;
			
			// aapt resource value: 0x7f060008
			public const int temperature = 2131099656;
			
			// aapt resource value: 0x7f060014
			public const int tvLatest = 2131099668;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int Main = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int serial_console = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int TempModTest = 2130903042;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f050001
			public const int ApplicationName = 2131034113;
			
			// aapt resource value: 0x7f050000
			public const int Hello = 2131034112;
			
			// aapt resource value: 0x7f050002
			public const int app_name = 2131034114;
			
			// aapt resource value: 0x7f050003
			public const int refreshing = 2131034115;
			
			// aapt resource value: 0x7f050004
			public const int sleep = 2131034116;
			
			// aapt resource value: 0x7f050005
			public const int sleep1 = 2131034117;
			
			// aapt resource value: 0x7f050006
			public const int wakeup = 2131034118;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Xml
		{
			
			// aapt resource value: 0x7f040000
			public const int device_filter = 2130968576;
			
			static Xml()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Xml()
			{
			}
		}
	}
}
#pragma warning restore 1591
