#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("TempModTest_MLX906.Resource", IsApplication=true)]

namespace TempModTest_MLX906
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
			global::Hoho.Android.UsbSerial.Resource.String.ApplicationName = global::TempModTest_MLX906.Resource.String.ApplicationName;
			global::Hoho.Android.UsbSerial.Resource.String.Hello = global::TempModTest_MLX906.Resource.String.Hello;
		}
		
		public partial class Array
		{
			
			// aapt resource value: 0x7f060000
			public const int fps_array = 2131099648;
			
			static Array()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Array()
			{
			}
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int Icon = 2130837504;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f070007
			public const int Get = 2131165191;
			
			// aapt resource value: 0x7f070005
			public const int Init41 = 2131165189;
			
			// aapt resource value: 0x7f070006
			public const int Init42 = 2131165190;
			
			// aapt resource value: 0x7f070019
			public const int backToDeviceList = 2131165209;
			
			// aapt resource value: 0x7f07000e
			public const int clear = 2131165198;
			
			// aapt resource value: 0x7f07000b
			public const int consoleText = 2131165195;
			
			// aapt resource value: 0x7f07000a
			public const int demoScroller = 2131165194;
			
			// aapt resource value: 0x7f070001
			public const int demoTitle = 2131165185;
			
			// aapt resource value: 0x7f070004
			public const int deviceList = 2131165188;
			
			// aapt resource value: 0x7f070017
			public const int editEmissivity = 2131165207;
			
			// aapt resource value: 0x7f070015
			public const int editTBOffset = 2131165205;
			
			// aapt resource value: 0x7f07001c
			public const int graphView = 2131165212;
			
			// aapt resource value: 0x7f07001a
			public const int linearLayout1 = 2131165210;
			
			// aapt resource value: 0x7f07001b
			public const int linearLayout2 = 2131165211;
			
			// aapt resource value: 0x7f070010
			public const int loadFromEEPROM = 2131165200;
			
			// aapt resource value: 0x7f07000f
			public const int loadFromFile = 2131165199;
			
			// aapt resource value: 0x7f070002
			public const int progressBar = 2131165186;
			
			// aapt resource value: 0x7f070000
			public const int progressBarTitle = 2131165184;
			
			// aapt resource value: 0x7f070018
			public const int saveTBCorrection = 2131165208;
			
			// aapt resource value: 0x7f070011
			public const int saveToEEPROM = 2131165201;
			
			// aapt resource value: 0x7f070003
			public const int separator = 2131165187;
			
			// aapt resource value: 0x7f070009
			public const int sleepButton = 2131165193;
			
			// aapt resource value: 0x7f070013
			public const int spinnerFPS = 2131165203;
			
			// aapt resource value: 0x7f07000c
			public const int start = 2131165196;
			
			// aapt resource value: 0x7f07000d
			public const int stop = 2131165197;
			
			// aapt resource value: 0x7f070008
			public const int temperature = 2131165192;
			
			// aapt resource value: 0x7f070016
			public const int tvEmissivity = 2131165206;
			
			// aapt resource value: 0x7f070012
			public const int tvFps = 2131165202;
			
			// aapt resource value: 0x7f07001d
			public const int tvLatest = 2131165213;
			
			// aapt resource value: 0x7f070014
			public const int tvOffset = 2131165204;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int Main = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int serial_console = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int TempModTest = 2130903042;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f050001
			public const int ApplicationName = 2131034113;
			
			// aapt resource value: 0x7f050000
			public const int Hello = 2131034112;
			
			// aapt resource value: 0x7f050002
			public const int app_name = 2131034114;
			
			// aapt resource value: 0x7f050009
			public const int emissivity = 2131034121;
			
			// aapt resource value: 0x7f050008
			public const int fps = 2131034120;
			
			// aapt resource value: 0x7f050007
			public const int offset = 2131034119;
			
			// aapt resource value: 0x7f050003
			public const int refreshing = 2131034115;
			
			// aapt resource value: 0x7f050004
			public const int sleep = 2131034116;
			
			// aapt resource value: 0x7f050005
			public const int sleep1 = 2131034117;
			
			// aapt resource value: 0x7f050006
			public const int wakeup = 2131034118;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Xml
		{
			
			// aapt resource value: 0x7f040000
			public const int device_filter = 2130968576;
			
			static Xml()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Xml()
			{
			}
		}
	}
}
#pragma warning restore 1591
