using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

using Android.App;
using Android.Content;
using Android.OS;
using Android.Runtime;
using Android.Views;
using Android.Widget;

namespace TempModTest_MLX906
{
    class ParameterCodesEEPROM
    {
        public const int CodeOscTrim = 1;
        public const int CodeAnalogTrim = 2;
        public const int CodeConfiguration = 3;
        public const int CodeI2CAddr = 4;
        public const int CodeCropPageAddr = 5;
        public const int CodeCropCellAddr = 6;
        public const int CodeControl1 = 7;
        public const int CodeControl2 = 8;
        public const int CodeI2CConf = 9;
        public const int CodeID1 = 10;
        public const int CodeID2 = 11;
        public const int CodeID3 = 12;
        public const int CodeDeviceOptions = 13;
        public const int CodeAnalogTrim2 = 14;
        public const int CodeScale_Occ_rem = 15;
        public const int CodeScale_Occ_col = 16;
        public const int CodeScale_Occ_row = 17;
        public const int CodeAlpha_PTAT = 18;
        public const int CodePix_os_average = 19;
        public const int CodeOCC_row = 20;
        public const int CodeOCC_column = 21;
        public const int CodeScale_Acc_rem = 22;
        public const int CodeScale_Acc_col = 23;
        public const int CodeScale_Acc_row = 24;
        public const int CodeAlpha_scale = 25;
        public const int CodePix_sens_average = 26;
        public const int CodeACC_row = 27;
        public const int CodeACC_column = 28;
        public const int CodeGAIN = 29;
        public const int CodePTAT_25 = 30;
        public const int CodeKt_PTAT = 31;
        public const int CodeKv_PTAT = 32;
        public const int CodeVdd_25 = 33;
        public const int CodeK_Vdd = 34;
        public const int CodeKv_Avg_RE_CE = 35;
        public const int CodeKv_Avg_RO_CE = 36;
        public const int CodeKv_Avg_RE_CO = 37;
        public const int CodeKv_Avg_RO_CO = 38;
        public const int CodeKta_Avg_RE_CO = 39;
        public const int CodeKta_Avg_RO_CO = 40;
        public const int CodeKta_Avg_RE_CE = 41;
        public const int CodeKta_Avg_RO_CE = 42;
        public const int CodeKta_scale2 = 43;
        public const int CodeKta_scale1 = 44;
        public const int CodeKv_scale = 45;
        public const int CodeRes_control = 46;
        public const int CodeAlpha_CP_P0 = 47;
        public const int CodeAlpha_CP_P1_P0 = 48;
        public const int CodeOffset_CP_P0 = 49;
        public const int CodeOffset_CP_P1_P0 = 50;
        public const int CodeKta_CP = 51;
        public const int CodeKv_CP = 52;
        public const int CodeTGC = 53;
        public const int CodeKsTa = 54;
        public const int CodeKsTo_R1 = 55;
        public const int CodeKsTo_R2 = 56;
        public const int CodeKsTo_R3 = 57;
        public const int CodeKsTo_R4 = 58;
        public const int CodeScale_KsTo = 59;
        public const int CodeCT1 = 60;
        public const int CodeCT2 = 61;
        public const int CodeTemp_Step = 62;
        public const int CodePixel_Kta = 63;
        public const int CodePixel_Alpha = 64;
        public const int CodePixel_Offset = 65;
        public const int CodeScale_occ_os = 66;
        public const int CodePix_os_avg = 67;
        public const int CodeKta_avg = 68;
        public const int CodeKta_scale_2 = 69;
        public const int CodeKta_scale_1 = 70;
        public const int CodeKv_avg = 71;
        public const int CodeKv_scale_2 = 72;
        public const int CodeKv_scale_1 = 73;
        public const int CodeScale_row = 74;
        public const int CodeRow_max = 75;
        public const int CodeEmissivity = 76;
        public const int CodeAlpha_CP = 77;
        public const int CodeAlpha_CP_scale = 78;
        public const int CodeOffset_CP = 79;
        public const int CodeKta_CP_scale = 80;
        public const int CodeKv_CP_scale = 81;
        public const int CodeCalib_res_cont = 82;
        public const int CodeKsTo_scale = 83;
        public const int CodeKsTo = 84;
        public const int CodePixel_os = 85;
        public const int CodePixel_Sensitivity = 86;
        public const int CodePixel_Kv = 87;
    }
}